baseurl = "http://clhjoe.github.io/"
languageCode = "zh-tw"
title = "Joe's Notes"
theme = "purehugo"
Paginate = 10
disqusShortname="joes-blog-4"
[params]
  githubName = "clhjoe"
  linkedinName = "智霖-黃-00594981"
  description = "備忘錄.."
  google_analytics = "UA-3749757-2"
